In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [2]:
df = pd.DataFrame({
       "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
    
})

In [3]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [4]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [5]:
pd.Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype = 'object')

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [6]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [7]:
x = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [8]:
x

    soil_moisture  temperature_c  sunlight_hours
0            0.10             34               9
1            0.15             30               8
2            0.20             26               7
3            0.25             22               4
4            0.40             28               8
5            0.60             30              10
6            0.35             19               3
7            0.18             22              10
8            0.45             35              12
9            0.05             24               5
10           0.80             33               9
11           0.27             33              11
12           0.55             21               2
13           0.70             25               6
14           0.12             20               1
15           0.30             29               9

In [9]:
y

0     1
1     1
2     1
3     0
4     0
5     0
6     0
7     1
8     0
9     1
10    0
11    1
12    0
13    0
14    1
15    1
Name: needs_water, dtype: int64

In [10]:
x_min = x.min()
x_max = x.max()
x_scaled = (x - x_min)/(x_max - x_min + 1e-8)

In [11]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [12]:
x_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [13]:
x_train, x_test, y_train, y_test = train_test_split(
    x_scaled, y, test_size = 0.25, random_state = 42, stratify = y)

In [14]:
model = keras.Sequential([
    layers.Input(shape = (x_train.shape[1],)),
    layers.Dense(8, activation = 'relu'),#first hidden layer
    layers.Dense(1, activation = 'sigmoid') #to get the output
])

In [15]:
model.compile(optimizer  = 'sgd', loss = 'binary_crossentropy', metrics = ['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [16]:
history = model.fit(x_train.values, y_train.values, 
                    validation_data = (x_test.values, y_test.values),
                                       epochs = 100, batch_size = 4, verbose = 1)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 233ms/step - accuracy: 0.5000 - loss: 0.6793 - val_accuracy: 0.5000 - val_loss: 0.6970
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5000 - loss: 0.6791 - val_accuracy: 0.5000 - val_loss: 0.6963
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5000 - loss: 0.6785 - val_accuracy: 0.5000 - val_loss: 0.6956
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5000 - loss: 0.6767 - val_accuracy: 0.5000 - val_loss: 0.6949
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5000 - loss: 0.6767 - val_accuracy: 0.5000 - val_loss: 0.6942
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.5000 - loss: 0.6780 - val_accuracy: 0.7500 - val_loss: 0.6936
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.5000 - loss: 0.6743 - val_accuracy: 0.7500 - val_loss: 0.6929
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5000 - loss: 0.6770 - val_accuracy: 0.7500 - val_loss: 0.6923
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.5000 - loss: 0.6728 - val_accuracy: 0.7500 - val_loss: 0.6916
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.5000 - loss: 0.6727 - val_accuracy: 0.7500 - val_loss: 0.6910
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.5000 - loss: 0.6713 - val_accuracy: 0.7500 - val_loss: 0.6904
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.5000 - loss: 0.6712 - val_accuracy: 0.7500 - val_loss: 0.6897
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.5000 - loss: 0.6705 - val_accuracy: 0.7500 - val_loss: 0.6891
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5000 - loss: 0.6700 - val_accuracy: 0.7500 - val_loss: 0.6885
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.5000 - loss: 0.6685 - val_accuracy: 0.7500 - val_loss: 0.6879
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.5000 - loss: 0.6686 - val_accuracy: 0.7500 - val_loss: 0.6873
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.5000 - loss: 0.6672 - val_accuracy: 0.7500 - val_loss: 0.6867
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.5000 - loss: 0.6672 - val_accuracy: 0.7500 - val_loss: 0.6862
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5000 - loss: 0.6669 - val_accuracy: 0.7500 - val_loss: 0.6856
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5000 - loss: 0.6662 - val_accuracy: 0.7500 - val_loss: 0.6850
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5000 - loss: 0.6657 - val_accuracy: 0.7500 - val_loss: 0.6845
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.5000 - loss: 0.6640 - val_accuracy: 0.7500 - val_loss: 0.6839
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5833 - loss: 0.6643 - val_accuracy: 0.7500 - val_loss: 0.6834
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5833 - loss: 0.6628 - val_accuracy: 0.7500 - val_loss: 0.6828
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5833 - loss: 0.6631 - val_accuracy: 0.7500 - val_loss: 0.6823
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5833 - loss: 0.6616 - val_accuracy: 0.7500 - val_loss: 0.6817
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.5833 - loss: 0.6618 - val_accuracy: 0.7500 - val_loss: 0.6812
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.5833 - loss: 0.6613 - val_accuracy: 0.7500 - val_loss: 0.6806
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5833 - loss: 0.6606 - val_accuracy: 0.7500 - val_loss: 0.6801
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.5833 - loss: 0.6599 - val_accuracy: 0.7500 - val_loss: 0.6796
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - accuracy: 0.5833 - loss: 0.6587 - val_accuracy: 0.7500 - val_loss: 0.6790
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.5833 - loss: 0.6601 - val_accuracy: 0.7500 - val_loss: 0.6786
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.5833 - loss: 0.6584 - val_accuracy: 0.7500 - val_loss: 0.6781
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.5833 - loss: 0.6576 - val_accuracy: 0.7500 - val_loss: 0.6777
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.5833 - loss: 0.6576 - val_accuracy: 0.7500 - val_loss: 0.6772
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.5833 - loss: 0.6566 - val_accuracy: 0.7500 - val_loss: 0.6768
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5833 - loss: 0.6560 - val_accuracy: 0.7500 - val_loss: 0.6764
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.5833 - loss: 0.6557 - val_accuracy: 0.7500 - val_loss: 0.6759
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.5833 - loss: 0.6542 - val_accuracy: 0.7500 - val_loss: 0.6755
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.5833 - loss: 0.6545 - val_accuracy: 0.7500 - val_loss: 0.6750
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.5000 - loss: 0.6539 - val_accuracy: 0.7500 - val_loss: 0.6746
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.5833 - loss: 0.6526 - val_accuracy: 0.7500 - val_loss: 0.6741
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.5833 - loss: 0.6528 - val_accuracy: 0.7500 - val_loss: 0.6737
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.5000 - loss: 0.6514 - val_accuracy: 0.7500 - val_loss: 0.6733
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.5000 - loss: 0.6509 - val_accuracy: 0.7500 - val_loss: 0.6728
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5000 - loss: 0.6512 - val_accuracy: 0.7500 - val_loss: 0.6724
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.5833 - loss: 0.6504 - val_accuracy: 0.7500 - val_loss: 0.6719
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.5000 - loss: 0.6498 - val_accuracy: 0.7500 - val_loss: 0.6715
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.5000 - loss: 0.6496 - val_accuracy: 0.7500 - val_loss: 0.6710
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.5000 - loss: 0.6487 - val_accuracy: 0.5000 - val_loss: 0.6706
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.5000 - loss: 0.6483 - val_accuracy: 0.5000 - val_loss: 0.6701
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.5833 - loss: 0.6477 - val_accuracy: 0.5000 - val_loss: 0.6697
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5833 - loss: 0.6467 - val_accuracy: 0.5000 - val_loss: 0.6692
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.5833 - loss: 0.6468 - val_accuracy: 0.5000 - val_loss: 0.6688
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5833 - loss: 0.6463 - val_accuracy: 0.5000 - val_loss: 0.6683
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5833 - loss: 0.6459 - val_accuracy: 0.5000 - val_loss: 0.6679
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5833 - loss: 0.6445 - val_accuracy: 0.5000 - val_loss: 0.6675
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5833 - loss: 0.6461 - val_accuracy: 0.5000 - val_loss: 0.6670
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.5833 - loss: 0.6441 - val_accuracy: 0.5000 - val_loss: 0.6666
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5833 - loss: 0.6428 - val_accuracy: 0.5000 - val_loss: 0.6662
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5833 - loss: 0.6430 - val_accuracy: 0.5000 - val_loss: 0.6658
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.6667 - loss: 0.6419 - val_accuracy: 0.5000 - val_loss: 0.6653
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.6667 - loss: 0.6420 - val_accuracy: 0.5000 - val_loss: 0.6649
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.6667 - loss: 0.6407 - val_accuracy: 0.5000 - val_loss: 0.6645
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.6667 - loss: 0.6402 - val_accuracy: 0.5000 - val_loss: 0.6640
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5833 - loss: 0.6425 - val_accuracy: 0.5000 - val_loss: 0.6636
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.6667 - loss: 0.6414 - val_accuracy: 0.5000 - val_loss: 0.6632
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.6667 - loss: 0.6394 - val_accuracy: 0.7500 - val_loss: 0.6627
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.6667 - loss: 0.6386 - val_accuracy: 0.7500 - val_loss: 0.6623
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.6667 - loss: 0.6382 - val_accuracy: 0.7500 - val_loss: 0.6619
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.6667 - loss: 0.6400 - val_accuracy: 0.7500 - val_loss: 0.6614
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.6667 - loss: 0.6401 - val_accuracy: 0.7500 - val_loss: 0.6610
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.6667 - loss: 0.6359 - val_accuracy: 0.7500 - val_loss: 0.6605
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.7500 - loss: 0.6360 - val_accuracy: 0.7500 - val_loss: 0.6601
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.7500 - loss: 0.6349 - val_accuracy: 0.7500 - val_loss: 0.6597
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.7500 - loss: 0.6350 - val_accuracy: 0.7500 - val_loss: 0.6592
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.7500 - loss: 0.6344 - val_accuracy: 0.7500 - val_loss: 0.6588
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.7500 - loss: 0.6340 - val_accuracy: 0.7500 - val_loss: 0.6583
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.7500 - loss: 0.6326 - val_accuracy: 0.7500 - val_loss: 0.6579
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.7500 - loss: 0.6322 - val_accuracy: 0.7500 - val_loss: 0.6574
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.7500 - loss: 0.6323 - val_accuracy: 0.7500 - val_loss: 0.6570
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.7500 - loss: 0.6317 - val_accuracy: 0.7500 - val_loss: 0.6565
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.7500 - loss: 0.6332 - val_accuracy: 0.7500 - val_loss: 0.6560
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.7500 - loss: 0.6300 - val_accuracy: 0.7500 - val_loss: 0.6556
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.7500 - loss: 0.6304 - val_accuracy: 0.7500 - val_loss: 0.6551
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.7500 - loss: 0.6310 - val_accuracy: 0.7500 - val_loss: 0.6547
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.7500 - loss: 0.6291 - val_accuracy: 0.7500 - val_loss: 0.6542
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.7500 - loss: 0.6303 - val_accuracy: 0.7500 - val_loss: 0.6537
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.7500 - loss: 0.6281 - val_accuracy: 0.7500 - val_loss: 0.6533
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.7500 - loss: 0.6275 - val_accuracy: 0.7500 - val_loss: 0.6528
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.7500 - loss: 0.6261 - val_accuracy: 0.7500 - val_loss: 0.6523
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.7500 - loss: 0.6279 - val_accuracy: 0.7500 - val_loss: 0.6519
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.7500 - loss: 0.6256 - val_accuracy: 0.7500 - val_loss: 0.6514
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.7500 - loss: 0.6246 - val_accuracy: 0.7500 - val_loss: 0.6509
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.7500 - loss: 0.6250 - val_accuracy: 0.7500 - val_loss: 0.6504
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.7500 - loss: 0.6241 - val_accuracy: 0.7500 - val_loss: 0.6500
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.7500 - loss: 0.6229 - val_accuracy: 0.7500 - val_loss: 0.6495
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.7500 - loss: 0.6229 - val_accuracy: 0.7500 - val_loss: 0.6490
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.7500 - loss: 0.6218 - val_accuracy: 0.7500 - val_loss: 0.6485
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.7500 - loss: 0.6235 - val_accuracy: 0.7500 - val_loss: 0.6481

In [ ]:
from tensorflow.keras import optimizers
#after that we can use different optimizers